[
    {
        "id" : "0",
        "company": "CH Robinson",
        "origin": "Golden, CO",
        "destination": "San Antonio, TX",
        // "deadhead_miles" : 150,
        "total_miles": 941.1,
        "equipment": "Van",
        "length": "53", // feet
        "weight": "33000",
        "f/p": "Full",
        "date_posted": "2022-04-24T21:46:20.974Z",
        "rate": 2597,
        "commodity": "General Freight",
        "comments": "Call DAT (800) 551-8847 for details",
        "factor": true,
        "reference_number": "217247"
    },
    {
        "id" : "1",
        "company": "Landstar System",
        "origin": "Texarkana, AR",
        "destination": "Atlanta, GA",
        // "deadhead_miles" : 150,
        "total_miles": 669.2,
        "equipment": "Van",
        "length": "53", // feet
        "weight": "40000",
        "f/p": "Full",
        "date_posted": "2022-04-24T22:13:36.512Z",
        "rate": 1505.96,
        "commodity": "Alchohol",
        "comments": "Must have empty weight before loading.  Loading is on a first come, first serve basis. Shipping hours are M-F 8am to 5pm.",
        "factor": true,
        "reference_number": "217248"
    },
    {
        "id" : "2",
        "company": "Odyssey Logistics",
        "origin": "Texas City, TX",
        "destination": "Monaca, PA",
        // "deadhead_miles" : 150,
        "total_miles": 1360.3,
        "equipment": "Tanker",
        "length": "43", // feet
        "weight": "45000",
        "f/p": "Full",
        "date_posted": "2022-04-24T22:24:21.970Z",
        "rate": 5512.34,
        "commodity": "Hazardous Materials",
        "comments": "All drivers required to have a valid TWIC card when entering plant. Trailer must be dry and odor free.  Trailer must be a DOT-407 belly insulated, equipped with 3in male camlock fitting at discharge valve. Hoses to be provided by customer.",
        "factor": true,
        "reference_number": "217249"
    },
    {
        "id" : "3",
        "company": "Coyote Logistics",
        "origin": "City of Industry, CA",
        "destination": "Richmond, VA",
        // "deadhead_miles" : 150,
        "total_miles": 2605.8,
        "equipment": "Reefer",
        "length": "53", // feet
        "weight": "41,000",
        "f/p": "Full",
        "date_posted": "2022-04-24T22:37:56.812Z",
        "rate": 5500,
        "commodity": "Produce",
        "comments": "Trailer must have proof of washout and and a tempature of -10° prior to entering facility. Call DAT (800) 551-8847 for details",
        "factor": false,
        "reference_number": "217250"
    },
    {
        "id" : "4",
        "company": "Total Quality Logistics",
        "origin": "Aurora, IL",
        "destination": "Newberry, SC",
        // "deadhead_miles" : 150,
        "total_miles": 800,
        "equipment": "Reefer",
        "length": "53", // feet
        "weight": "35,000",
        "f/p": "Full",
        "date_posted": "2022-04-24T22:42:42.937Z",
        "rate": 1750.38,
        "commodity": "Produce",
        "comments": "Drivers must slide tandems to rear prior to entering shipper.  Unloading hours are 24/7, fcfs.",
        "factor": true,
        "reference_number": "217251"
    },
    {
        "id" : "5",
        "company": "Odyssey Logistics",
        "origin": "Channahon, IL",
        "destination": "La Porte, TX",
        // "deadhead_miles" : 150,
        "total_miles": 1040,
        "equipment": "Tanker",
        "length": "43", // feet
        "weight": "35,000",
        "f/p": "Full",
        "date_posted": "2022-04-24T23:02:06.185Z",
        "rate": 3432.66,
        "commodity": "Hazardous Materials",
        "comments": "All drivers required to have a valid TWIC card when entering plant. Trailer must be clean, dry, and odor free.  Trailer must be a DOT-407 rear insulated, equipped with 3in male camlock fitting at discharge valve. 40ft of hoses to be provided by driver.",
        "factor": true,
        "reference_number": "217252"
    },
]